### ISSUE TITLE
Mock slave configuration lacks Description field

### ISSUE THREAD

**Issue by quietust** [jenkinsci/mock-slave-plugin#3]
When creating or editing a mock slave, you cannot set its Description because the field is missing; if you edit the slave's config.xml directly, however, it shows up correctly in the appropriate places.

In my case, I'm using mock slaves to represent remote UNIX systems (e.g. AIX, HP-UX, Linux s390x) which do not have versions of Java capable of running the Jenkins Slave Agent (and which are non-trivial to acquire) and only using "Execute shell" steps consisting of SSH commands (which were previously always executed on Master).

**Comment by jglick** [comment]
Please use JIRA for filing issues.

You are not using this plugin for its intended purpose. Try the SSH plugin instead.
